version: '3.6'
services:
  db:
    image: postgres:12.4
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_PASSWORD: awesomepostgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8081:8080
